name: Docker Image CI

on:
  push:
    branches: [ "master" ]
env:
  AWS_REGION: ap-southeast-2
  ECR_REPOSITORY: cobosys
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: 'gradle'

    - name: Run chmod to make gradlew executable
      run: chmod +x gradlew

    - name: Gradle BUild Movie
      uses: gradle/gradle-build-action@v3
      with:
        arguments: build

    - name: Docker build movie-api
      run: docker build -t cobosys .

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Publish Image to ECR
      run: |
        docker tag cobosys:latest ${{ secrets.ECR_URI }}:latest
        docker push ${{ secrets.ECR_URI }}:latest
